# syntax=docker/dockerfile:1.4
FROM python:3 as base

###

FROM base
WORKDIR /app

RUN pip install poetry
ENV POETRY_VIRTUALENVS_IN_PROJECT=true
ENV POETRY_CACHE_DIR=/cache

RUN --mount=type=cache,id=apt-cache,target=/var/lib/apt/lists/ apt-get update
RUN --mount=type=cache,id=apt-cache,target=/var/lib/apt/lists/ apt-get install -y --no-install-recommends dumb-init

ADD pyproject.toml pyproject.toml
ADD poetry.lock poetry.lock

RUN --mount=type=tmpfs,target=/app/.venv --mount=type=cache,id=poetry-cache,target=/cache \
    poetry install

ADD . .

RUN --network=none --mount=type=cache,id=dev-dependencies,target=/app/.venv --mount=type=cache,id=poetry-cache,target=/cache \
    poetry install
RUN --mount=type=cache,id=dev-dependencies,target=/app/.venv /app/.venv/bin/pytest /app

ENV FLASK_APP=app
ENTRYPOINT ["dumb-init"]
CMD ["/app/.venv/bin/flask", "run"]
