FROM python:3 as base

###

FROM base
WORKDIR /app

RUN pip install poetry
ENV POETRY_VIRTUALENVS_IN_PROJECT=true
ENV POETRY_CACHE_DIR=/cache

RUN --mount=type=cache,id=apt-cache,target=/var/lib/apt/lists/ apt-get update
RUN --mount=type=cache,id=apt-cache,target=/var/lib/apt/lists/ apt-get install -y --no-install-recommends dumb-init

ADD pyproject.toml pyproject.toml
ADD poetry.lock poetry.lock

RUN --mount=type=cache,id=poetry-cache,target=/app/.venv \
    poetry install --no-dev

ADD . .

ENV FLASK_APP=app
ENTRYPOINT ["dumb-init"]
CMD ["/app/.venv/bin/flask", "run"]
