FROM python:3 as base

###

FROM base AS dependencies
WORKDIR /app
ARG PYPI_USERNAME
ARG PYPI_PASSWORD

RUN pip install poetry
ENV POETRY_VIRTUALENVS_IN_PROJECT=true
ENV POETRY_CACHE_DIR=/cache

ADD pyproject.toml pyproject.toml
ADD poetry.lock poetry.lock

RUN POETRY_HTTP_BASIC_ENTWICKLERHELD_USERNAME=$PYPI_USERNAME POETRY_HTTP_BASIC_ENTWICKLERHELD_PASSWORD=$PYPI_PASSWORD poetry install --no-dev

###

FROM base
WORKDIR /app

RUN --mount=type=cache,id=apt-cache,target=/var/lib/apt/lists/ apt-get update
RUN --mount=type=cache,id=apt-cache,target=/var/lib/apt/lists/ apt-get install -y --no-install-recommends dumb-init

ADD . .
COPY --from=dependencies /app/.venv /app/.venv

ENV FLASK_APP=app
ENTRYPOINT ["dumb-init"]
CMD ["/app/.venv/bin/flask", "run"]
