FROM python:3

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends dumb-init \
    && rm -rf /var/lib/apt/lists/*

RUN pip install poetry
ENV POETRY_VIRTUALENVS_IN_PROJECT=true
ENV POETRY_CACHE_DIR=/cache

ADD pyproject.toml pyproject.toml
ADD poetry.lock poetry.lock

RUN poetry install --no-dev

ADD . .

ENV FLASK_APP=app
ENTRYPOINT ["dumb-init"]
CMD ["/app/.venv/bin/flask", "run"]
