FROM python:3 as base

###

FROM base AS dependencies
WORKDIR /app

RUN pip install poetry
ENV POETRY_VIRTUALENVS_IN_PROJECT=true
ENV POETRY_CACHE_DIR=/cache

ADD pyproject.toml pyproject.toml
ADD poetry.lock poetry.lock

RUN poetry install --no-dev

###

FROM base
WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends dumb-init \
    && rm -rf /var/lib/apt/lists/*

ADD . .
COPY --from=dependencies /app/.venv /app/.venv

ENV FLASK_APP=app
ENTRYPOINT ["dumb-init"]
CMD ["/app/.venv/bin/flask", "run"]
