name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./dockerfiles/Dockerfile.1
        build-args: |
          PYPI_USERNAME=${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD=${{ secrets.PYPI_PASSWORD }}
        tags: |
          ghcr.io/polylith/docker-on-steroids-1:latest
        push: true
  build2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./dockerfiles/Dockerfile.2
        build-args: |
          PYPI_USERNAME=${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD=${{ secrets.PYPI_PASSWORD }}
        tags: |
          ghcr.io/polylith/docker-on-steroids-2:latest
        push: true
  build1-inline-cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./dockerfiles/Dockerfile.1
        build-args: |
          PYPI_USERNAME=${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD=${{ secrets.PYPI_PASSWORD }}
        tags: |
          ghcr.io/polylith/docker-on-steroids-1-inline-cache:latest
        push: true
        cache-from: type=registry,ref=ghcr.io/polylith/docker-on-steroids-1-inline-cache:latest
        cache-to: type=inline
  build2-inline-cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./dockerfiles/Dockerfile.2
        build-args: |
          PYPI_USERNAME=${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD=${{ secrets.PYPI_PASSWORD }}
        tags: |
          ghcr.io/polylith/docker-on-steroids-2-inline-cache:latest
        push: true
        cache-from: type=registry,ref=ghcr.io/polylith/docker-on-steroids-2-inline-cache:latest
        cache-to: type=inline
  build2-registry-cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./dockerfiles/Dockerfile.2
        build-args: |
          PYPI_USERNAME=${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD=${{ secrets.PYPI_PASSWORD }}
        tags: |
          ghcr.io/polylith/docker-on-steroids-2:latest
        push: true
        cache-from: type=registry,ref=ghcr.io/polylith/docker-on-steroids-2:buildcache
        cache-to: type=registry,ref=ghcr.io/polylith/docker-on-steroids-2:buildcache,mode=max
  build3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./dockerfiles/Dockerfile.3
        build-args: |
          PYPI_USERNAME=${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD=${{ secrets.PYPI_PASSWORD }}
        tags: |
          ghcr.io/polylith/docker-on-steroids-3:latest
        push: true
        cache-from: type=registry,ref=ghcr.io/polylith/docker-on-steroids-3:buildcache
        cache-to: type=registry,ref=ghcr.io/polylith/docker-on-steroids-3:buildcache,mode=max
  build4:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./dockerfiles/Dockerfile.4
        build-args: |
          PYPI_USERNAME=${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD=${{ secrets.PYPI_PASSWORD }}
        tags: |
          ghcr.io/polylith/docker-on-steroids-4:latest
        push: true
        cache-from: type=registry,ref=ghcr.io/polylith/docker-on-steroids-4:buildcache
        cache-to: type=registry,ref=ghcr.io/polylith/docker-on-steroids-4:buildcache,mode=max
  build5:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./dockerfiles/Dockerfile.5
        build-args: |
          PYPI_USERNAME=${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD=${{ secrets.PYPI_PASSWORD }}
        tags: |
          ghcr.io/polylith/docker-on-steroids-5:latest
        push: true
        cache-from: type=registry,ref=ghcr.io/polylith/docker-on-steroids-5:buildcache
        cache-to: type=registry,ref=ghcr.io/polylith/docker-on-steroids-5:buildcache,mode=max
  build6:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./dockerfiles/Dockerfile.6
        build-args: |
          PYPI_USERNAME=${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD=${{ secrets.PYPI_PASSWORD }}
        tags: |
          ghcr.io/polylith/docker-on-steroids-6:latest
        push: true
        cache-from: type=registry,ref=ghcr.io/polylith/docker-on-steroids-6:buildcache
        cache-to: type=registry,ref=ghcr.io/polylith/docker-on-steroids-6:buildcache,mode=max
  build7:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./dockerfiles/Dockerfile.7
        build-args: |
          PYPI_USERNAME=${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD=${{ secrets.PYPI_PASSWORD }}
        tags: |
          ghcr.io/polylith/docker-on-steroids-7:latest
        push: true
        cache-from: type=registry,ref=ghcr.io/polylith/docker-on-steroids-7:buildcache
        cache-to: type=registry,ref=ghcr.io/polylith/docker-on-steroids-7:buildcache,mode=max