name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./dockerfiles/Dockerfile.1
        build-args: |
          PYPI_USERNAME=${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD=${{ secrets.PYPI_PASSWORD }}
        tags: |
          ghcr.io/polylith/docker-on-steroids-1:latest
        push: true
  build2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./dockerfiles/Dockerfile.2
        build-args: |
          PYPI_USERNAME=${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD=${{ secrets.PYPI_PASSWORD }}
        tags: |
          ghcr.io/polylith/docker-on-steroids-2:latest
        push: true
  build3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./dockerfiles/Dockerfile.2
        build-args: |
          PYPI_USERNAME=${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD=${{ secrets.PYPI_PASSWORD }}
        tags: |
          ghcr.io/polylith/docker-on-steroids-2-with-cache:latest
        push: true
        cache-from: type=registry,ref=ghcr.io/polylith/docker-on-steroids-2-with-cache:latest
        cache-to: type=inline